/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspaceWorkspaceIdIndexRouteImport } from './routes/_authenticated/workspace/$workspaceId/index'
import { Route as AuthenticatedWorkspaceWorkspaceIdSettingsRouteImport } from './routes/_authenticated/workspace/$workspaceId/settings'
import { Route as AuthenticatedWorkspaceWorkspaceIdProjectsProjectIdIndexRouteImport } from './routes/_authenticated/workspace/$workspaceId/projects/$projectId/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceWorkspaceIdIndexRoute =
  AuthenticatedWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/workspace/$workspaceId/',
    path: '/workspace/$workspaceId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdSettingsRoute =
  AuthenticatedWorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/workspace/$workspaceId/settings',
    path: '/workspace/$workspaceId/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceIdProjectsProjectIdIndexRoute =
  AuthenticatedWorkspaceWorkspaceIdProjectsProjectIdIndexRouteImport.update({
    id: '/workspace/$workspaceId/projects/$projectId/',
    path: '/workspace/$workspaceId/projects/$projectId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workspace/$workspaceId/settings': typeof AuthenticatedWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/': typeof AuthenticatedWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/projects/$projectId/': typeof AuthenticatedWorkspaceWorkspaceIdProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workspace/$workspaceId/settings': typeof AuthenticatedWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId': typeof AuthenticatedWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/projects/$projectId': typeof AuthenticatedWorkspaceWorkspaceIdProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/workspace/$workspaceId/settings': typeof AuthenticatedWorkspaceWorkspaceIdSettingsRoute
  '/_authenticated/workspace/$workspaceId/': typeof AuthenticatedWorkspaceWorkspaceIdIndexRoute
  '/_authenticated/workspace/$workspaceId/projects/$projectId/': typeof AuthenticatedWorkspaceWorkspaceIdProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/workspace/$workspaceId/settings'
    | '/_authenticated/workspace/$workspaceId/'
    | '/_authenticated/workspace/$workspaceId/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace/$workspaceId/': {
      id: '/_authenticated/workspace/$workspaceId/'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/$workspaceId/settings': {
      id: '/_authenticated/workspace/$workspaceId/settings'
      path: '/workspace/$workspaceId/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/$workspaceId/projects/$projectId/': {
      id: '/_authenticated/workspace/$workspaceId/projects/$projectId/'
      path: '/workspace/$workspaceId/projects/$projectId'
      fullPath: '/workspace/$workspaceId/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspaceWorkspaceIdSettingsRoute: typeof AuthenticatedWorkspaceWorkspaceIdSettingsRoute
  AuthenticatedWorkspaceWorkspaceIdIndexRoute: typeof AuthenticatedWorkspaceWorkspaceIdIndexRoute
  AuthenticatedWorkspaceWorkspaceIdProjectsProjectIdIndexRoute: typeof AuthenticatedWorkspaceWorkspaceIdProjectsProjectIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspaceWorkspaceIdSettingsRoute:
    AuthenticatedWorkspaceWorkspaceIdSettingsRoute,
  AuthenticatedWorkspaceWorkspaceIdIndexRoute:
    AuthenticatedWorkspaceWorkspaceIdIndexRoute,
  AuthenticatedWorkspaceWorkspaceIdProjectsProjectIdIndexRoute:
    AuthenticatedWorkspaceWorkspaceIdProjectsProjectIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
